### PR TITLE
Adding -H (Header) as a global option

### PR DESCRIPTION
**Pull request by kjshomper**
Our team would like to make use of the apigeetool; however, we're behind a company proxy and need to provide authorization to get out to the internet and hit the api.enterprise.apigee.com endpoint.  CNTLM is an option for local development environments, but doesn't work well in CI pipelines.

I added two changes:

1. Added a global -H header option to provide additional headers from the command line.

1. Extended the option descriptors to allow multiples and updated the option parsing code to push multiple option values onto an array.  I did not alter defaults.js to consume multiples on any options other than header.  I left that as a change awaiting a use case that needed multiples on other options.

So these changes should be fully compatible with any prior use, but does extend capability for those who need to set headers.

### CODE REVIEW

**Comment by kjshomper** [comment]
I signed the CLA.

**Comment by kjshomper** [comment]
Added a fix.  It appears the intent of the help output was to show required when the option must be included on the command line.  Although this wasn't the behavior.

Before (fetchproxy -help example) , if the option was required and the program prompted for it, it would show as required, which is was, but not on the command line.  Other required options, not prompted for, like API or Organization, were listed in the help as optional.  This is confusing, because supplying only username and password still resulted in an error message identifying the required options.

After: if the option is required and not prompted for (false) or prompt is undefined, then the program will not obtain the value and should fail, therefore, the options should be listed as required (for the command line).  If the option is required and prompted for, i.e. prompt: true, then it's still optional on the command line,, because it will prompt.  If the option isn't required, it's optional.  Changing the test on prompt to a NOT test, fixes the behavior.

**Comment by AdamMagaluk** [comment]
LGTM except can you add a note in the READ.md for the flag. It should go in the `Common Parameters` section.
 
Thanks

**Comment by AdamMagaluk** [comment]
Looks good just need to remove `.vscode/launch.json` file.

**Comment by kjshomper** [comment]
Done.  Didn't think on the git status and used the git add . by mistake.

**Comment by kjshomper** [comment]
Thanks for checking.

**Comment by AdamMagaluk** [comment]
LGTM, thanks for the addition!

**Pull request merged**
