### PR TITLE
Ignore uploading of root devDependencies

### PR DESCRIPTION
**Pull request by confuser**
I've added mocha as the example package to ignore within the `enumerateNodeDirectory` test.

Please note, this does not ignore `devDependencies` of your `dependencies` as that would require full traversal of the entire node_modules directory and reading every package.json file; but rather your project's dev dependencies.

i.e. if your package depends on `express`, that modules `devDependencies` will still be uploaded

### CODE REVIEW

**Comment by theganyo** [comment]
This seems like a reasonable enhancement, but it seems the PR is broken as it lists 270 files as changed. Thus, I'm closing without merging.

**Comment by confuser** [comment]
Those changes are installing a new module committed into the repo as stated
in my PR

**Comment by theganyo** [comment]
Oh, ok. I see what you did. Was it really necessary to include all of mocha into the repo? I don't think that's a good idea.

**Comment by confuser** [comment]
No but it already contained the entire of express, and that appeared to be
the way you were performing tests in this repo, so I merely followed that

**Comment by theganyo** [comment]
Wow. Yeah, you're right. I hadn't realized that was there. It looks like we should address that as well. Thanks.

**Pull request closed without merging**
