### PR TITLE
Implementation of #128 (attributes on developer create) and #129 (create key secret)

### PR DESCRIPTION
**Pull request by DavePickard1234**
Added the ability to set custom attributes when creating a developer.
Added the ability to set a custom key / secret for dev app against specific products.  This functionality is via sdk only.

### CODE REVIEW

**Comment by DavePickard1234** [comment]
I signed it!

**Comment by AdamMagaluk** [comment]
Any reason why we wouldn't add it to the CLI in this file https://github.com/apigee/apigeetool-node/blob/master/lib/commands/commands.js

Other than that LGTM

**Comment by DavePickard1234** [comment]
Hi,

No real reason not to put into CLI.  I think I observed that there were one or two commands that didn't have CLI and as I didn't require it I left it out.  Happy to add in if it's felt that that would be best practice.

**Comment by AdamMagaluk** [comment]
We can table for another PR but i think it would be useful.

**Comment by AdamMagaluk** [comment]
+1

**Comment by DavePickard1234** [comment]
Thanks @AdamMagaluk .  I'll create a separate issue to implement for CLI and look to get it addressed.  How is this PR pushed through?

**Comment by DavePickard1234** [comment]
Thanks @KyleWiese - I've corrected those comments.

**Comment by whitlockjc** [comment]
My only request would be to break these up into separate PRs since there are two features and two issues being resolved.

**Comment by whitlockjc** [comment]
For consistency, would it make sense to rename `createkeysecret` to be `createAppKey`?  Right now, `createApp` is for creating a developer application and really, we're creating a key for a developer application.  To me, I think `createAppKey` is the appropriate name.  Beyond this change, I think I agree with the rest of the PR and will gladly merge both fixes in one instead of asking you to break them up.

**Comment by DavePickard1234** [comment]
Thanks @whitlockjc.  I've updated the name.  Will make sure any further dev work will stick to one issue per pull request.

**Comment by whitlockjc** [comment]
Done.  Thanks for your work!

**Comment by DavePickard1234** [comment]
Thanks @whitlockjc .  Is there a process for getting a new release done?

**Pull request merged**
