### PR TITLE
added apiproxy delete and undeploy sharedflow commands to SDK

### PR DESCRIPTION
**Pull request by dmmsonos**
These appear to have been accidental omissions, very simple code additions.

### CODE REVIEW

**Comment by dmmsonos** [comment]
I signed it!

**Comment by whitlockjc** [comment]
LGTM _(but I'd like to have someone else look too)_

**Comment by dmmsonos** [comment]
@whitlockjc any way you could get someone else to take a look? This is a blocker for me. Would really appreciate it

**Comment by whitlockjc** [comment]
I'll get it merged in and a release cut today.  I'm traveling so if you've not heard from me by EOD, ping me here.

**Comment by dmmsonos** [comment]
Fantastic thanks so much!

**Comment by dmmsonos** [comment]
@whitlockjc ping

**Comment by whitlockjc** [comment]
`apigeetool@0.9.1` has these changes in it, thanks again for your contributions!

**Pull request merged**
