### PR TITLE
Fixes for issues 158,159,160,161,162,163, improved local and remote tests

### PR DESCRIPTION
**Pull request by kurtkanaskie**
Fixed bugs and updated tests. 
Remote tests still need some work, but works fine for newly added features.
npm test
npm run remotetest

### CODE REVIEW

**Comment by whitlockjc** [comment]
I hate to request this but it would be really nice if this PR were split up into separate PRs per issue/feature _(where possible)_.  This makes it much easier to trace changes, rollback things _(if needed)_, etc.

**Comment by kurtkanaskie** [comment]
I was afraid of that, I found bugs while building new features and just fixed them and added Issues for tracking. If you want, I can separate into individual PRs. Do I have to wait for each merge or can I stack up PRs, one per issue?

**Comment by whitlockjc** [comment]
Stack them and I'll merge in order.  I apologize for asking for this but I think it makes sense.  As for fixing bugs in a PR, I'm fine with that.  Title your commit based on what you're doing, and then add a note into the commit referring to fixing a bug.  Example:

```
Added support for ...

* This commit also includes a bug fix found while doing the work, the
bug fixed is ...
```

This is just an example, format and word however you want.

**Comment by kurtkanaskie** [comment]
OK, how about this, I'll fix the latest issue #165 "remotetests" and add in bug fixes for #158 #160 #161 and #163 all related to options. Then I'll do #162 then #159 
So 3 PRs in total, does that work?

**Comment by whitlockjc** [comment]
Sounds good.

**Comment by kurtkanaskie** [comment]
Closing and redoing incremental PRs

**Pull request closed without merging**
