### PR TITLE
Correctly implement the deployproxy to deploy in one zip

### PR DESCRIPTION
**Pull request by DinoChiesa**
This PR combines two key changes: 
- deployproxy command now creates a single ZIP and imports that. This required a change in the deployproxy.js file as well as in ziputils.js
- the .netrc option is -N, not -n
- correctly implement and document the --base-path option.

### CODE REVIEW

**Comment by gbrail** [comment]
OK, I'll bite. Why is this "correct?"

On Tue, Jul 5, 2016 at 8:21 PM, Dino Chiesa <notifications@github.com>
wrote:

> This PR combines two key changes:
>
>    - deployproxy command now creates a single ZIP and imports that. This
>    required a change in the deployproxy.js file as well as in ziputils.js
>    - the .netrc option is -N, not -n
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apigee/apigeetool-node/pull/43
> Commit Summary
>
>    - remove -base-path option from deployproxy command. This option is
>    not documented in the public API and ought not be used. Also, it's
>    unnecessary here. It is necessary in deploynodeapp, but not here.
>    - Revert "remove -base-path option from deployproxy command. This
>    option is not documented in the public API and ought not be used. Also,
>    it's unnecessary here. It is necessary in deploynodeapp, but not here."
>    - correctly implement the -base-path option in deployproxy command
>    - fixup deployproxy to create and import a single zip for the proxy
>    bundle
>    - correct the option to read .netrc. It is -N
>    - correct the README to document the .netrc option properly
>
> File Changes
>
>    - *M* README.md
>    <https://github.com/apigee/apigeetool-node/pull/43/files#diff-0> (4)
>    - *M* lib/commands/deployproxy.js
>    <https://github.com/apigee/apigeetool-node/pull/43/files#diff-1> (717)
>    - *M* lib/defaults.js
>    <https://github.com/apigee/apigeetool-node/pull/43/files#diff-2> (2)
>    - *M* lib/ziputils.js
>    <https://github.com/apigee/apigeetool-node/pull/43/files#diff-3> (58)
>
> Patch Links:
>
>    - https://github.com/apigee/apigeetool-node/pull/43.patch
>    - https://github.com/apigee/apigeetool-node/pull/43.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apigee/apigeetool-node/pull/43>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAf0a78rkLJOD3pVr6_uzkG_RNZ1Is8yks5qSx8lgaJpZM4JFuKW>
> .
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by DinoChiesa** [comment]
The original "deployproxy" command created a one-file zip, then wrapped up resources, targets, proxies,... and basically manually wrapped up and pushed the proxy bundle in N different http calls.  What this new operation does is zip everytihng from the api proxy bundle into a single zip and import it as a unit.  This is correct because it's so much simpler. Also it is future-proof as it will work with other directories or other files. For example, there's an outstanding request to allow a Readme.md in an apiproxy bundle, that would be displayed on the overview tab in the Edge UI.  The current deployproxy command would reject any proxy bundle directory containing that file.  This modified version does not reject it.

**Comment by gbrail** [comment]
What happens if the proxy contains large Node modules? The original reason
for breaking it up rather than using the big ZIP was because the Edge API
would reject any Zipped proxy that has more than 15 MB of stuff in it. With
this change, "deployproxy" won't work for those kinds of proxies unless we
have changed the way that the public API works.

On Wed, Jul 6, 2016 at 10:23 AM, Dino Chiesa <notifications@github.com>
wrote:

> The original "deployproxy" command created a one-file zip, then wrapped up
> resources, targets, proxies,... and basically manually wrapped up and
> pushed the proxy bundle in N different http calls. What this new operation
> does is zip everytihng from the api proxy bundle into a single zip and
> import it as a unit. This is correct because it's so much simpler. Also it
> is future-proof as it will work with other directories or other files. For
> example, there's an outstanding request to allow a Readme.md in an apiproxy
> bundle, that would be displayed on the overview tab in the Edge UI. The
> current deployproxy command would reject any proxy bundle directory
> containing that file. This modified version does not reject it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apigee/apigeetool-node/pull/43#issuecomment-230843517>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAf0a3vIH29YRoCLEXAbSR6rFAxF8YJ7ks5qS-SKgaJpZM4JFuKW>
> .
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by DinoChiesa** [comment]
The "remoteNpm" (--resolve-modules or -R) option still works as before. If the user specifies -R on the command line, then it means the node_modules directory is not included in the zip, nor is any node_modules.zip file that may exist. Instead it zips the package.json and later uses the Edge admin API to call "npm install".  The code that does this is unchanged from before.  The only change relevant to large proxies is... instead of zipping each category of thing (targets, proxies, resources, etc), there is one zip file created, containing all the things.  That zip-bundle will either include or not include the node_modules, depending on the -R option.

**Comment by gbrail** [comment]
Ok, but that means that with this change, apigeetool won't work with
proxies that have large Node bundles and don't want to / can't use the
"resolve" option. So I don't think that we should to this.

On Wed, Jul 6, 2016 at 11:14 AM, Dino Chiesa <notifications@github.com>
wrote:

> The "remoteNpm" (--resolve-modules or -R) option still works as before. If
> the user specifies -R on the command line, then it means the node_modules
> directory is not included in the zip, nor is any node_modules.zip file that
> may exist. Instead it zips the package.json and later uses the Edge admin
> API to call "npm install". The code that does this is unchanged from
> before. The only change relevant to large proxies is... instead of zipping
> each category of thing (targets, proxies, resources, etc), there is one zip
> file created, containing all the things. That zip-bundle will either
> include or not include the node_modules, depending on the -R option.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apigee/apigeetool-node/pull/43#issuecomment-230858238>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAf0a5px9_Q9gPXAgCUwnstY3D7esjJsks5qS_CJgaJpZM4JFuKW>
> .
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by DinoChiesa** [comment]
That's correct - if there is a large bundle and the person does not want to remotely resolve, then... this change won't accommodate that person. I could rework it to allow a new option to do the segmented upload. I will look at re-submitting.

**Comment by gbrail** [comment]
Or if we could prevail on the Edge team to make sure that the "import" API
can support streaming uploads, then go for it!

And thanks for submitting a PR!

On Wed, Jul 6, 2016 at 11:21 AM, Dino Chiesa <notifications@github.com>
wrote:

> Closed #43 <https://github.com/apigee/apigeetool-node/pull/43>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apigee/apigeetool-node/pull/43#event-714730107>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAf0a0L_lKLOjaj1rSbzZ3KNm-cO2ygfks5qS_I7gaJpZM4JFuKW>
> .
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Pull request closed without merging**
