### PR TITLE
Support proxy and flows update revision

### PR DESCRIPTION
**Pull request by nikitwaghelasonos**
* update revision for proxy
* updtae revision for sharedflow
flag: --revision|-r #number

### CODE REVIEW

**Comment by nikitwaghelasonos** [comment]
@googlebot I signed it!

**Comment by nikitwaghelasonos** [comment]
@googlebot I signed it!

**Comment by gvasconcellos** [comment]
Any plans for this? Looking forward to it.

**Comment by whitlockjc** [comment]
@DinoChiesa Can you take a peek at this to verify with me?

**Pull request closed without merging**
